### PR TITLE
Generate -debug flag for flang1

### PR DESCRIPTION
**Pull request by vjayathirtha-nv**

### CODE REVIEW

**Comment by vjayathirtha-nv** [comment]
@schweitzpgi

**Comment by vjayathirtha-nv** [comment]
@kiranchandramohan  We have mechanism in the flang-driver to indicate all the temp files that we generate in flang1, flang2 which then get deleted by the driver.

https://github.com/flang-compiler/flang-driver/blob/9579fb8086134d4b9963a572b1b65df823169028/lib/Driver/ToolChains/Flang.cpp#L820

https://github.com/flang-compiler/flang-driver/blob/9579fb8086134d4b9963a572b1b65df823169028/lib/Driver/ToolChains/Flang.cpp#L825

https://github.com/flang-compiler/flang-driver/blob/9579fb8086134d4b9963a572b1b65df823169028/lib/Driver/ToolChains/Flang.cpp#L830

The ".dbg" file was not added to this list of temp files when when I enabled the `-debug` flag for flang1. I will fix this.

**Comment by kiranchandramohan** [comment]
@vjayathirtha-nv Thanks for the quick response.

Are you referring to the qfile option to flang1 which accepts a filename for the debug file and sets "dbgfile"?
  register_string_arg(arg_parser, "qfile", &dbgfile, NULL);

But this does not seem to be connected to the following code which depends on "dbg_file".
   if (OUTPUT_DWARF && (dbg_file == NULL)) {
      /* make dwarf debug info file from the source file */
      if (outfile_name != NULL) {
        mkDwfInfoFilename();
      } else {
        dbg_file_name = mkfname(sourcefile, file_suffix, ".dbg");
      }
      if ((dbg_file = fopen(dbg_file_name, "wb")) == NULL)
        errfatal(9);
    }

**Comment by vjayathirtha-nv** [comment]
@kiranchandramohan Sorry I should've been clearer. No, I'm not referring to register_string_arg() in flang1. The macro `OUTPUT_DWARF` ties into PGI proprietary code. In my earlier comment I was considering allowing flang1 to generate the `.dbg` file and cleaning it up using the [flang-driver](https://github.com/flang-compiler/flang-driver) at the end of compilation. On second thoughts I think we could manage said macro to not generate the temp file at all. I will work to get that change into flang1.

**Comment by kiranchandramohan** [comment]
Thanks @vjayathirtha-nv , please close https://github.com/flang-compiler/flang/issues/727 when the issue is fixed.

**Pull request merged**
