### PR TITLE
Add clangFrontend dependency flang-compiler/flang-driver#70

### PR DESCRIPTION
**Pull request by isuruf**
Fixes https://github.com/flang-compiler/flang/issues/747

### CODE REVIEW

**Comment by schweitzpgi** [comment]
Is Flang.cpp introducing some new (possibly circular?) library dependence?  I'm asking because I wonder if some code in that compilation unit is misplaced and should live elsewhere.

**Comment by isuruf** [comment]
The definitions of `DefineTypeSize` lives in `clangFrontend`. It was introduced in https://github.com/flang-compiler/flang-driver/pull/70/files#diff-083ee342d5d83f15e63043222f8c8b10
I previously had a copy of those two tiny functions in `Flang.cpp`, but was told to re-use the original functions in https://github.com/flang-compiler/flang-driver/pull/70#discussion_r284846177

**Comment by vjayathirtha-nv** [comment]
`clangFrontend` does depend on `clangDriver` 
https://github.com/flang-compiler/flang-driver/blob/f4508c0261f0c0a5920d850e6d0a769fadd17e00/lib/Frontend/CMakeLists.txt#L58

So this PR would introduce circular dependency.

**Comment by isuruf** [comment]
So, should I go back to copying the two functions to `Flang.cpp` then?

**Comment by isuruf** [comment]
Superceded by #86

**Pull request closed without merging**
