### PR TITLE
Use predefined macros from clang preprocessor - release_70 branch

### PR DESCRIPTION
**Pull request by isuruf**
@vjayathirtha-nv, I couldn't check that this works because there were some unrelated errors. (Maybe a mismatch between LLVM version and clang here) Would you be able to check that this compiles?

### CODE REVIEW

**Comment by vjayathirtha-nv** [comment]
I've built and tested this branch. It works for me.
Were you trying to build flang-driver release_70 branch with an LLVM branch other than release_70 ?

**Comment by isuruf** [comment]
> Were you trying to build flang-driver release_70 branch with an LLVM branch other than release_70 ?

I was using a binary package from my package manager. (I only had LLVM 6.0 built from source)

**Comment by vjayathirtha-nv** [comment]
OK.

**Comment by isuruf** [comment]
Thanks @vjayathirtha-nv for the review

**Comment by vjayathirtha-nv** [comment]
You're welcome

**Pull request merged**
